service: sls-lambda-dima  

plugins: 
  - serverless-offline

frameworkVersion: '2'

package:
  exclude:
    - .git/**
    - .vscode/**
    - dynamo/**
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  memorySize: 2048
  timeout: 30
  stage: dev
  region: us-east-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:*
        - s3:*
        - cloudformation:*
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

  environment:
    STAGE: ${opt:stage, 'dev'}
    ACCESS_KEY_ID: ${ssm:/dima_access_key_id}
    SECRET_ACCESS_KEY: ${ssm:/dima_secret_access_key}
    USER_POOL_ID: ${ssm:/dima_user_pool_id}
    APP_CLIENT_ID: ${ssm:/dima_app_client_id}

functions:
  createPost:
    handler: handler.index
    events:
     - http:
         path: /poster/add
         method: POST
         cors: true
         private: false
  deletePost:
    handler: handler.index
    events:
     - http:
         path: /poster/delete
         method: POST
         cors: true
         private: false
  getPostById:
    handler: handler.index
    events:
     - http:
         path: /poster/update/{id}
         method: GET
         cors: true
         private: false
  updatePost:
    handler: handler.index
    events:
     - http:
         path: /poster/update
         method: POST
         cors: true
         private: false
  getPosts:
    handler: handler.index
    events:
     - http:
         path: /poster
         method: GET
         cors: true
         private: false 
  signIn: 
    handler: handler.index
    events:
      - http:
         path : /auth/login
         method: POST
         cors: true
         private: false
  signUp:
    handler: handler.index
    events:
      - http:
         path : /auth/register
         method: POST
         cors: true
         private: false
  logout:
    handler: handler.index
    events: 
      - http:
         path: /auth/logout
         method: POST
         cors: true
         private: false
  refreshToken:
    handler: handler.index
    events: 
      - http:
         path: /auth/refreshtoken
         method: POST
         cors: true
         private: false
    
